[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "24"
  BUN_VERSION = "1.3.11"

# Astro config redirect causes visual reload in prod
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  force = true

[[headers]]
  for = "/_astro/*.js"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*.css"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*.webp"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/fonts/*"
  [headers.values]
    cache-control = "public, max-age=604800"
