name: Build dist

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
      - run: bun install --frozen-lockfile
      - run: bun run build
